name: process-pull-request

on:
  pull_request_target:
    types: [ opened, reopened, edited, review_requested, ready_for_review, assigned ]

# FIXME: Use `main` instead of `CURA-10831` once merged
jobs:
  add_label:
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/process-pull-request.yml@main
    secrets: inherit
